CREATE DATABASE IdealHome;
USE IdealHome;

-- USERS TABLE
CREATE TABLE users (
    UserID INT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Address TEXT,
    Age INT,
    NIC VARCHAR(20) UNIQUE,
    ContactInfo VARCHAR(100),
    Gender ENUM('Male','Female','Other'),
    ProfilePhotoPath VARCHAR(255),
    UserType ENUM('Student','HomeOwner') NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- STUDENTS TABLE
CREATE TABLE students (
    StudentID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL UNIQUE,
    University VARCHAR(100),
    Faculty VARCHAR(100),
    Department VARCHAR(100),
    FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE
);

-- HOME OWNERS TABLE
CREATE TABLE home_owners (
    OwnerID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL UNIQUE,
    Area VARCHAR(100),
    GoogleLocation VARCHAR(255),
    FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE
);

-- PROPERTIES TABLE (FIXED)
CREATE TABLE properties (
    PropertyID INT PRIMARY KEY AUTO_INCREMENT,
    OwnerID INT NULL,   -- ALLOW NULL TO PREVENT FK ERRORS
    Title VARCHAR(100) DEFAULT 'House',
    Address VARCHAR(255) NOT NULL,
    Price DECIMAL(10, 2),
    Rate DECIMAL(3,2),
    Description TEXT,
    PropertyImagePath VARCHAR(255),
    Status VARCHAR(20) DEFAULT 'Available',
    forRentOrSale ENUM('Sale','Rent') NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (OwnerID) REFERENCES home_owners(OwnerID)
        ON DELETE SET NULL      -- FIX: NO MORE FOREIGN KEY ERRORS
        ON UPDATE CASCADE
);

-- USER LISTS TABLE
CREATE TABLE user_lists (
    ListID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    PropertyID INT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES users(UserID) ON DELETE CASCADE,
    FOREIGN KEY (PropertyID) REFERENCES properties(PropertyID) ON DELETE CASCADE,
    UNIQUE KEY unique_user_property (UserID, PropertyID)
);

-- MULTI-IMAGE PROPERTY GALLERY TABLE
CREATE TABLE property_images (
    ImageID INT PRIMARY KEY AUTO_INCREMENT,
    PropertyID INT NOT NULL,
    ImagePath VARCHAR(255) NOT NULL,
    IsPrimary BOOLEAN DEFAULT FALSE,
    UploadedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PropertyID) REFERENCES properties(PropertyID) ON DELETE CASCADE
);
